# Generated by Django 5.1 on 2024-08-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stencils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stencil',
            name='stencil_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
