# Generated by Django 5.1.4 on 2025-01-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stenciltensionvalues',
            name='end_of_specific_range',
        ),
        migrations.RemoveField(
            model_name='stenciltensionvalues',
            name='start_of_specific_range',
        ),
    ]
