# Generated by Django 5.1.6 on 2025-02-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_stenciltensionvalues_end_of_specific_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stenciltensionvalues',
            name='description',
        ),
    ]
