# Generated by Django 5.1.6 on 2025-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_stenciltensionvalues_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterTension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('min_value', models.FloatField(default=0, null=True)),
                ('max_value', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
