# Generated by Django 5.1.6 on 2025-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_parametertension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametertension',
            name='parameter',
        ),
        migrations.AddField(
            model_name='parametertension',
            name='scratch_value',
            field=models.FloatField(default=0, null=True),
        ),
    ]
