# Generated by Django 5.1.6 on 2025-03-26 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_parametertension_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametertension',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
