# Generated by Django 5.1.6 on 2025-03-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_parametertension_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametertension',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
