# Generated by Django 5.1.6 on 2025-03-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_parametertension_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stenciltensionvalues',
            name='is_pending_measurement',
            field=models.BooleanField(default=False),
        ),
    ]
