# Generated by Django 5.1.6 on 2025-06-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_stenciltensionvalues_is_pending_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stenciltensionvalues',
            name='path_p1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stenciltensionvalues',
            name='path_p2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stenciltensionvalues',
            name='path_p3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stenciltensionvalues',
            name='path_p4',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
