# Generated by Django 5.1.6 on 2025-07-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_stenciltensionvalues_path_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stenciltensionvalues',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
