# stencils/models.py

from django.db import models

class Stencil(models.Model):
    stencil_id = models.BigIntegerField(primary_key=True)
    site_id = models.CharField(max_length=10)
    stencil_part_nbr = models.CharField(max_length=50)
    vendor_part_nbr = models.CharField(max_length=50)
    vendor = models.CharField(max_length=50)
    mfg_date = models.DateField()
    product_type = models.CharField(max_length=10)
    thickness = models.CharField(max_length=10)
    pcb_up_nbr = models.IntegerField()
    location = models.CharField(max_length=10)
    status = models.CharField(max_length=10)
    life_limit = models.IntegerField()
    counter = models.IntegerField()
    trigger_err_limit = models.IntegerField()
    reg_date_time = models.DateTimeField()
    reg_user_id = models.CharField(max_length=10)
    notes = models.TextField()
    update_user_id = models.CharField(max_length=10, null=True, blank=True)
    datetime = models.DateTimeField()
    revision = models.CharField(max_length=10)
    side = models.CharField(max_length=10)
    label_info = models.TextField()
    is_active_in_use = models.BooleanField()
    stencil_destination = models.CharField(max_length=10)
    p1_value = models.FloatField()
    p2_value = models.FloatField()
    p3_value = models.FloatField()
    p4_value = models.FloatField()
    is_blocked_stencil = models.BooleanField()
    index_of_suggested_stencil = models.IntegerField()
    object_status = models.CharField(max_length=50)
